ToDoList.Web/Controllers/UserController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;
using ToDoList.Data;

namespace ToDoList.Web.Controllers
{
    public class UserController : Controller
    {
        private readonly ToDoListContext db;
        public UserController(ToDoListContext _db)
        {
            db = _db;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Login()
        {
            return View();
        }
        [Authorize(Roles = "0")]
        public IActionResult Management()
        {
            return View();
        }
        public IActionResult GetAll(bool isActive)
        {
            var list = db.Users.Where(u => u.IsDeleted == false && u.IsActive == isActive)
                .Join(db.UserTypes, u => u.UserTypeId, t => t.Id,
                (users, types) => new
                {
                    fullName = users.FullName,
                    userName = users.UserName,
                    userType = types.Name,
                    id = users.Id
                }

                ).ToList();
            return Json(new { data = list });
        }
        [HttpPost]
        public string Delete(int id)
        {
            try
            {
                Models.User user = db.Users.AsNoTracking().FirstOrDefault(u => u.Id == id);
                user.IsDeleted = true;

                db.Users.Update(user);
                db.SaveChanges();

                return "Başarılı";
            }
            catch (Exception e)
            {
                return e.Message;
            }
        }
        [HttpPost]
        public async Task<IActionResult> Login(Models.User user)
        {

            Models.User isUser = db.Users.FirstOrDefault(u => u.UserName == user.UserName && u.PassWord == user.PassWord && u.IsDeleted == false && u.IsActive == true);
            if (isUser != null)
            {
                List<Claim> userClaims = new List<Claim>();

                userClaims.Add(new Claim(ClaimTypes.NameIdentifier, isUser.Id.ToString()));
                userClaims.Add(new Claim(ClaimTypes.Name, isUser.UserName));
                userClaims.Add(new Claim(ClaimTypes.GivenName, isUser.FullName));
                
                //admin ise 0
                //user ise 1  gelecek
                userClaims.Add(new Claim(ClaimTypes.Role, isUser.UserTypeId.ToString()));

                var claimsIdentity = new ClaimsIdentity(userClaims, CookieAuthenticationDefaults.AuthenticationScheme);


                var authProperties = new AuthenticationProperties
                {
                    IsPersistent = false

                };

                //Eger kullanıcı, loginli oldugu halde, login sayfasına ulaştıysa, karışıklık olmaması için, her loginden evvel, signout (logout) komutunu çalıştırıyoruz ki, temiz bir başlangıç yapalım.
                await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);


                //LOGIN OLMA AŞAMASI
                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity), authProperties);

                return RedirectToAction("Index", "Home");
            }
            else
            {
                return View(user);
            }
        }
        [HttpPost]
        public string Add(Models.User user)
        {
            if (user != null)
            {
                try
                {
                    db.Users.Add(user);
                    db.SaveChanges();
                    return db.Users.ToList().Last().Id.ToString();
                }
                catch (Exception e)
                {
                    return e.Message;
                }
            }
            return "HATA : Nesnenin içi boş";
        }
        public IActionResult GetUserById(int userId)
        {
            return Json(db.Users.Find(userId));
        }

        [HttpPost]
        public string Update(Models.User user)
        {
            Models.User old = db.Users.AsNoTracking().FirstOrDefault(u => u.Id == user.Id);
            user.DateCreated = old.DateCreated;
            user.IsActive = old.IsActive;
            user.IsDeleted = old.IsDeleted;
            user.ProfilePicture = old.ProfilePicture;

            db.Users.Update(user);
            db.SaveChanges();
            return "Başarılı";
        }
    }
}

ToDoList.Web/Controllers/UserTypeController.cs
using Microsoft.AspNetCore.Mvc;
using ToDoList.Data;

namespace ToDoList.Web.Controllers
{
    public class UserTypeController : Controller
    {
        //Dependency injection ile contextimizi aldık.
        private readonly ToDoListContext db;
        public UserTypeController(ToDoListContext _db)
        {
            db= _db;
        }


     
        public IActionResult GetAll()
        {

            return Json(db.UserTypes.ToList());
        }
    }
}

ToDoList.Web/Views/User/Login.cshtml
@model ToDoList.Models.User

@{
    Layout = null;
}
<html>




<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="author" content="Yinka Enoch Adedokun">
	 <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	  <link rel="stylesheet" href="~/css/Login.css" asp-append-version="true" />
	<title>Login Page</title>
</head>
<body>
	<!-- Main Content -->
	<div class="container-fluid">
		<div class="row main-content bg-success text-center">
			<div class="col-md-4 text-center company__info">
				<span class="company__logo"><h2><span class="fa fa-android"></span></h2></span>
				<h4 class="company_title">To Do list</h4>
			</div>
			<div class="col-md-8 col-xs-12 col-sm-12 login_form ">
				<div class="container-fluid">
					<div class="row">
						<h2>Giriş Yap</h2>
					</div>
					<div class="row">
						<form method="post" asp-action="Login" class="form-group">
							<div class="row">
								<input asp-for="UserName" class="form__input" placeholder="Kullanıcı adınızı giriniz">
							</div>
							<div class="row">
								<!-- <span class="fa fa-lock"></span> -->
								<input asp-for="PassWord" type="password" class="form__input" placeholder="Şifrenizi giriniz">
							</div>
							
							<div class="row">
								<input type="submit" value="Giriş" class="btn">
							</div>
						</form>
					</div>
					
				</div>
			</div>
		</div>
	</div>
	<!-- Footer -->

</body>
</html>

ToDoList.Web/Views/User/Management.cshtml
@section Styles
    {
    <link rel="stylesheet" href="//cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css" />
 }
    <div class="row">
        <div class="col-12 m-2">
            <a id="btnEkle" class="btn btn-success">Yeni Kullanıcı Ekle</a>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <table id="datatable" class="table table-bordered dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;">
                        <thead>
                            <tr>
                                <th>Ad Soyad</th>
                                <th>Kullanıcı Adı</th>
                                <th>Kullanıcı Tipi</th>
                                <th>İşlemler</th>
                            </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <partial name="_InsertUserModal" />
    @section Scripts
    {
    <script src="//cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript">

        var updateUserId;
       
        var DataTable;
        $(document).ready(
            function() {
                loadUserTypes();
                loadDataTable();
                $("#btnEkle").click(ShowUserInsertModal);
                $("#btnHideModal").click(HideUserInsertModal);
                $("#btnKapat").click(HideUserInsertModal);
                
            }
        );
        function loadDataTable() {
            DataTable = $('#datatable').DataTable(
                {
                    "ajax": { "url": "/User/GetAll?isActive=True" },
                    "columns": [
                        { "data": "fullName" },
                        { "data": "userName" },
                        { "data": "userType" },
                        {
                            "data": "id",
                            "render": function(data) {
                                return `
                                                <a onclick="ShowUserUpdateModal('${data}')" title="Düzenle" class="btn-success btn-sm" >Düzenle</a>
                                                <a onclick="DeleteConfirm('${data}')"  title="Sil" class="btn-danger btn-sm" >Sil</a>                    
                                                `
                            }
                        }
                    ]
                }
            );
        }
        function DeleteConfirm(id) {
            Swal.fire({
                title: 'Silmek istediğinizden emin misiniz?',
                showDenyButton: true,
                showCancelButton: true,
                confirmButtonText: 'Evet',
                denyButtonText: 'Hayır',
                cancelButtonText: 'İptal'
            }).
                then((result) => {  /* Read more about isConfirmed, isDenied below */
                    if (result.isConfirmed) {
                        Delete(id);
                    }
                    else if (result.isDenied) { Swal.fire('Değişiklikler iptal edildi', '', 'info') }
                })
        }
        function loadUserTypes() {
            var model;
            var url = "@Url.Action("GetAll","UserType")";
            $.getJSON(url, function(res) {
                var len = res.length;
                $("#ddlUserType").empty();
                for (var i = 0; i < len; i++) {
                    var id = res[i]['id'];
                    var name = res[i]['name'];
                    $("#ddlUserType").append("<option value='" + id + "'>" + name + "</option>");
                }
            });
        }
        function ShowUserInsertModal() {
            $("#fullName").val('');
            $("#userName").val('');
            $("#passWord").val('');
            $("#insertUserModal").modal('show');
            $("#btnGonder").unbind();
            $("#btnGonder").click(Add);
            $("#btnGonder").text("Ekle");
        }
        function ShowUserUpdateModal(id) {
            $("baslik").text("Kullanıcı Güncelle");
            $("#insertUserModal").modal('show');
            $("#btnGonder").text("Güncelle");
            $("#btnGonder").unbind();
            $("#btnGonder").click(UpdateUser);
            updateUserId = id;

            var data = { userId: id };
            var url = "@Url.Action("GetUserById","User")";
            $.post(url, data, function(get) {
                $("#fullName").val(get.fullName);
                $("#userName").val(get.userName);
                $("#passWord").val(get.passWord);
                $("#ddlUserType").val(get.userTypeId);

            });
        }
        function UpdateUser() {
            var UserModel = {
                id:updateUserId,
                fullName: $("#fullName").val(),
                userName: $("#userName").val(),
                passWord: $("#passWord").val(),
                userTypeId: $("#ddlUserType").val(),               
            };
            var url = "@Url.Action("Update","User")";
            console.log(UserModel);
            $.post(url, UserModel, function(res) {
                DataTable.ajax.reload();

                $("#insertUserModal").modal('hide');
            });
        }
        function HideUserInsertModal() {
            $("#insertUserModal").modal('hide');
        }
        function Delete(id) {
            var model = { id: id };
            var url = "@Url.Action("Delete","User")";
            $.post(url, model, function(res) {
                DataTable.ajax.reload();
            });
        }
        function Add() {
            var model = {
                fullName: $("#fullName").val(),
                userName: $("#userName").val(),
                passWord: $("#passWord").val(),
                userTypeId: $("#ddlUserType").val(),
                userTypeName: $("#ddlUserType option:selected").text()
            };
            var url = "@Url.Action("Add","User")";
            console.log(model);
            $.post(url, model, function(res) {
                $("#insertUserModal").modal('hide');
                DataTable.row.add({
                    "fullName": model.fullName,
                    "userName": model.userName,
                    "userType": model.userTypeName,
                    "id": res
                }).draw();
            });
        }
    </script>
 }