ToDoList.Web/Controllers/ToDoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;
using ToDoList.Data;
using ToDoList.Models;

namespace ToDoList.Web.Controllers
{
    public class ToDoController : Controller
    {
        private readonly ToDoListContext db;

        public ToDoController(ToDoListContext _db)
        {
            db = _db;
        }

        [Authorize]
        public IActionResult Index(int userId)
        {
            List<ToDo> list = db.ToDos.Where(t=>t.StatusId==1).Join(db.ToDoUserRels.Where(r=>r.UserId==userId), t => t.Id, r => r.ToDoId,
                (todo, rel) => new ToDo
                {
                    Description = todo.Description,
                    DateCreated = todo.DateCreated,
                    EndDate = todo.EndDate,
                    Id = todo.Id,
                    IsActive = todo.IsActive,
                    IsDeleted = todo.IsDeleted,
                    Status = todo.Status,
                    StatusId = todo.StatusId,

                }

                ).ToList<ToDo>();

            return View(list);
        }

        [Authorize]
        public IActionResult Complete(int toDoId)
        {
            //gelen id'yi kullanarak, veritabanında, ilgili todo kaydının StatusID'sini 2 (tamamlandı) yapalım.
            ToDo toDo = db.ToDos.Find(toDoId);
            toDo.StatusId = 2;
            db.ToDos.Update(toDo);
            db.SaveChanges();

            return RedirectToAction("Index", new { userId = User.Claims.First(c => c.Type == ClaimTypes.NameIdentifier).Value });


        }

        [HttpPost]
        public string CompleteAjax(ToDo todo)
        {
            ToDo old= db.ToDos.AsNoTracking().First(t=>t.Id==todo.Id);
            //gelen id'yi kullanarak, veritabanında, ilgili todo kaydının StatusID'sini 2 (tamamlandı) yapalım.

            todo.StatusId = 2;
            todo.Description = old.Description;
            todo.DateCreated = old.DateCreated;
            todo.IsDeleted = old.IsDeleted;
            todo.EndDate = old.EndDate;
            todo.IsActive = old.IsActive;
            db.ToDos.Update(todo);
            db.SaveChanges();

            return "Başarılı";



        }



        [HttpPost]
        public string Add(ToDo todo)
        {
            try
            {
                db.ToDos.Add(todo);
                db.SaveChanges();
                //son kaydolan Todo nesnesinin db deki Id sine ulaşmak için bunu yapıyoruz
                todo = db.ToDos.OrderBy(t => t.Id).Last();
                db.ToDoUserRels.Add(new ToDoUserRel { ToDoId = todo.Id, UserId = int.Parse(User.Claims.First(c => c.Type == ClaimTypes.NameIdentifier).Value) });
                db.SaveChanges();

                return "İşlem Başarılı";
            }
            catch (Exception e)
            {
                return e.Message;
            }


        }


        [HttpPost]
        public IActionResult GetAllByUserId(int userId)
        {
            List<ToDo> list = db.ToDos.Where(t => t.StatusId == 1).Join(db.ToDoUserRels.Where(r => r.UserId == userId), t => t.Id, r => r.ToDoId,
                (todo, rel) => new ToDo
                {
                    Description = todo.Description,
                    DateCreated = todo.DateCreated,
                    EndDate = todo.EndDate,
                    Id = todo.Id,
                    IsActive = todo.IsActive,
                    IsDeleted = todo.IsDeleted,
                    Status = todo.Status,
                    StatusId = todo.StatusId,

                }

                ).ToList<ToDo>();

            return Json(list);
        }



    }
}

ToDoList.Web/Controllers/UserController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;
using ToDoList.Data;

namespace ToDoList.Web.Controllers
{
    public class UserController : Controller
    {
        private readonly ToDoListContext db;
        public UserController(ToDoListContext _db)
        {
            db = _db;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Login()
        {
            return View();
        }
        [Authorize(Roles = "0")]
        public IActionResult Management()
        {
            return View();
        }
        public IActionResult GetAll(bool isActive)
        {
            var list = db.Users.Where(u => u.IsDeleted == false && u.IsActive == isActive)
                .Join(db.UserTypes, u => u.UserTypeId, t => t.Id,
                (users, types) => new
                {
                    fullName = users.FullName,
                    userName = users.UserName,
                    userType = types.Name,
                    id = users.Id
                }

                ).ToList();
            return Json(new { data = list });
        }
        [HttpPost]
        public string Delete(int id)
        {
            try
            {
                Models.User user = db.Users.AsNoTracking().FirstOrDefault(u => u.Id == id);
                user.IsDeleted = true;

                db.Users.Update(user);
                db.SaveChanges();

                return "Başarılı";
            }
            catch (Exception e)
            {
                return e.Message;
            }
        }
        [HttpPost]
        public async Task<IActionResult> Login(Models.User user)
        {

            Models.User isUser = db.Users.FirstOrDefault(u => u.UserName == user.UserName && u.PassWord == user.PassWord && u.IsDeleted == false && u.IsActive == true);
            if (isUser != null)
            {
                List<Claim> userClaims = new List<Claim>();

                userClaims.Add(new Claim(ClaimTypes.NameIdentifier, isUser.Id.ToString()));
                userClaims.Add(new Claim(ClaimTypes.Name, isUser.UserName));
                userClaims.Add(new Claim(ClaimTypes.GivenName, isUser.FullName));
                
                //admin ise 0
                //user ise 1  gelecek
                userClaims.Add(new Claim(ClaimTypes.Role, isUser.UserTypeId.ToString()));

                var claimsIdentity = new ClaimsIdentity(userClaims, CookieAuthenticationDefaults.AuthenticationScheme);


                var authProperties = new AuthenticationProperties
                {
                    IsPersistent = false

                };

                //Eger kullanıcı, loginli oldugu halde, login sayfasına ulaştıysa, karışıklık olmaması için, her loginden evvel, signout (logout) komutunu çalıştırıyoruz ki, temiz bir başlangıç yapalım.
                await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);


                //LOGIN OLMA AŞAMASI
                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity), authProperties);

                return RedirectToAction("Index", "Home");
            }
            else
            {
                return View(user);
            }
        }
        [HttpPost]
        public string Add(Models.User user)
        {
            if (user != null)
            {
                try
                {
                    db.Users.Add(user);
                    db.SaveChanges();
                    return db.Users.ToList().Last().Id.ToString();
                }
                catch (Exception e)
                {
                    return e.Message;
                }
            }
            return "HATA : Nesnenin içi boş";
        }
        public IActionResult GetUserById(int userId)
        {
            return Json(db.Users.Find(userId));
        }

        [HttpPost]
        public string Update(Models.User user)
        {
            Models.User old = db.Users.AsNoTracking().FirstOrDefault(u => u.Id == user.Id);
            user.DateCreated = old.DateCreated;
            user.IsActive = old.IsActive;
            user.IsDeleted = old.IsDeleted;
            user.ProfilePicture = old.ProfilePicture;

            db.Users.Update(user);
            db.SaveChanges();
            return "Başarılı";
        }
    }
}

ToDoList.Web/Views/Shared/_InsertToDoModal.cshtml
@using System.Security.Claims
<div class="modal fade" id="insertModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Yeni Görev Ekle</h5>
                <button type="button" id="btnHideModal" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form>
                    <div class="form-group">
                        <label class="col-form-label">Bitiş Tarihi:</label>
                        <input id="enddate" type="date" class="form-control">
                    </div>
                    <div class="form-group">
                        <label class="col-form-label">Görev Açıklaması:</label>
                        <textarea id="description" class="form-control"></textarea>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" id="btnKapat" class="btn btn-secondary" data-dismiss="modal">Kapat</button>
                <button type="button" id="btnGonder" class="btn btn-primary">Görev Ekle</button>
            </div>
        </div>
    </div>
</div>

ToDoList.Web/Views/Shared/_InsertUserModal.cshtml
<div class="modal fade" id="insertUserModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Yeni Kullanıcı Ekle</h5>
                <button type="button" id="btnHideModal" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form>
                    <div class="form-group">
                        <label class="col-form-label">Ad Soyad</label>
                        <input id="fullName" class="form-control">
                    </div>
                    <div class="form-group">
                        <label class="col-form-label">Kullanıcı Adı</label>
                        <input id="userName" class="form-control"></input>
                    </div>
                      <div class="form-group">
                        <label class="col-form-label">Şifre</label>
                        <input id="passWord" type="password" class="form-control"></input>
                    </div>
                    <div class="form-group">
                        <label class="col-form-label">Kullanıcı Tipi</label>
                         <select id="ddlUserType" class="form-control">
                    </select>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" id="btnKapat" class="btn btn-secondary" data-dismiss="modal">Kapat</button>
                <button type="button" id="btnGonder" class="btn btn-primary">Kullanıcı Ekle</button>
            </div>
        </div>
    </div>
</div>

ToDoList.Web/Views/Shared/_Layout.cshtml
@using System.Security.Claims
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ToDoList.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ToDoList.Web.styles.css" asp-append-version="true" />
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>   
    @await RenderSectionAsync("Styles", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">ToDo List</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Görevler</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-action="Index" asp-route-userId="@Context.User.Claims.First(c=>c.Type==System.Security.Claims.ClaimTypes.NameIdentifier).Value" asp-controller="ToDo">Listele</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Profilim</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">İstatistikler</a>
                        </li>
                        @if (Context.User.Claims.First(c => c.Type == System.Security.Claims.ClaimTypes.Role).Value == "0")
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-action="Management" asp-controller="User">Kullanıcı Yönetimi</a>
                            </li>
                        }
                    </ul>
                    <form class="d-flex">
                        <input class="form-control me-sm-2" type="text" placeholder="Ara">
                        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Ara</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ToDoList.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
        @await RenderSectionAsync("Scripts", required: false)
</body>
</html>